
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActionServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/ActionService?wsdl")
public class ActionServiceService
    extends Service
{

    private final static URL ACTIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIONSERVICESERVICE_EXCEPTION;
    private final static QName ACTIONSERVICESERVICE_QNAME = new QName("http://endpoint.service/", "ActionServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/ActionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIONSERVICESERVICE_WSDL_LOCATION = url;
        ACTIONSERVICESERVICE_EXCEPTION = e;
    }

    public ActionServiceService() {
        super(__getWsdlLocation(), ACTIONSERVICESERVICE_QNAME);
    }

    public ActionServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIONSERVICESERVICE_QNAME, features);
    }

    public ActionServiceService(URL wsdlLocation) {
        super(wsdlLocation, ACTIONSERVICESERVICE_QNAME);
    }

    public ActionServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIONSERVICESERVICE_QNAME, features);
    }

    public ActionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActionService
     */
    @WebEndpoint(name = "ActionServicePort")
    public ActionService getActionServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "ActionServicePort"), ActionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns ActionService
     */
    @WebEndpoint(name = "ActionServicePort")
    public ActionService getActionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "ActionServicePort"), ActionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIONSERVICESERVICE_EXCEPTION!= null) {
            throw ACTIONSERVICESERVICE_EXCEPTION;
        }
        return ACTIONSERVICESERVICE_WSDL_LOCATION;
    }

}
