
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.ListOfAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ActionService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface ActionService {


    /**
     * 
     * @return
     *     returns types.ListOfAction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAction", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllAction")
    @ResponseWrapper(localName = "getAllActionResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllActionResponse")
    @javax.xml.ws.Action(input = "http://endpoint.service/ActionService/getAllActionRequest", output = "http://endpoint.service/ActionService/getAllActionResponse")
    public ListOfAction getAllAction();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfAction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewAction", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewAction")
    @ResponseWrapper(localName = "setNewActionResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewActionResponse")
    @javax.xml.ws.Action(input = "http://endpoint.service/ActionService/setNewActionRequest", output = "http://endpoint.service/ActionService/setNewActionResponse")
    public ListOfAction setNewAction(
        @WebParam(name = "arg0", targetNamespace = "")
        types.Action arg0);

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotal", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetTotal")
    @ResponseWrapper(localName = "getTotalResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetTotalResponse")
    @javax.xml.ws.Action(input = "http://endpoint.service/ActionService/getTotalRequest", output = "http://endpoint.service/ActionService/getTotalResponse")
    public double getTotal();

}
