
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BranchServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/BranchService?wsdl")
public class BranchServiceService
    extends Service
{

    private final static URL BRANCHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BRANCHSERVICESERVICE_EXCEPTION;
    private final static QName BRANCHSERVICESERVICE_QNAME = new QName("http://endpoint.service/", "BranchServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/BranchService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BRANCHSERVICESERVICE_WSDL_LOCATION = url;
        BRANCHSERVICESERVICE_EXCEPTION = e;
    }

    public BranchServiceService() {
        super(__getWsdlLocation(), BRANCHSERVICESERVICE_QNAME);
    }

    public BranchServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BRANCHSERVICESERVICE_QNAME, features);
    }

    public BranchServiceService(URL wsdlLocation) {
        super(wsdlLocation, BRANCHSERVICESERVICE_QNAME);
    }

    public BranchServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BRANCHSERVICESERVICE_QNAME, features);
    }

    public BranchServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BranchServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BranchService
     */
    @WebEndpoint(name = "BranchServicePort")
    public BranchService getBranchServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "BranchServicePort"), BranchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns BranchService
     */
    @WebEndpoint(name = "BranchServicePort")
    public BranchService getBranchServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "BranchServicePort"), BranchService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BRANCHSERVICESERVICE_EXCEPTION!= null) {
            throw BRANCHSERVICESERVICE_EXCEPTION;
        }
        return BRANCHSERVICESERVICE_WSDL_LOCATION;
    }

}
