
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.Branch;
import types.ListOfBranch;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BranchService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface BranchService {


    /**
     * 
     * @return
     *     returns types.ListOfBranch
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBranch", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllBranch")
    @ResponseWrapper(localName = "getAllBranchResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllBranchResponse")
    @Action(input = "http://endpoint.service/BranchService/getAllBranchRequest", output = "http://endpoint.service/BranchService/getAllBranchResponse")
    public ListOfBranch getAllBranch();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfBranch
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBranch", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DeleteBranch")
    @ResponseWrapper(localName = "deleteBranchResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DeleteBranchResponse")
    @Action(input = "http://endpoint.service/BranchService/deleteBranchRequest", output = "http://endpoint.service/BranchService/deleteBranchResponse")
    public ListOfBranch deleteBranch(
        @WebParam(name = "arg0", targetNamespace = "")
        Branch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfBranch
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewBranch", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewBranch")
    @ResponseWrapper(localName = "setNewBranchResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewBranchResponse")
    @Action(input = "http://endpoint.service/BranchService/setNewBranchRequest", output = "http://endpoint.service/BranchService/setNewBranchResponse")
    public ListOfBranch setNewBranch(
        @WebParam(name = "arg0", targetNamespace = "")
        Branch arg0);

}
