
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MaterialServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/MaterialService?wsdl")
public class MaterialServiceService
    extends Service
{

    private final static URL MATERIALSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MATERIALSERVICESERVICE_EXCEPTION;
    private final static QName MATERIALSERVICESERVICE_QNAME = new QName("http://endpoint.service/", "MaterialServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/MaterialService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATERIALSERVICESERVICE_WSDL_LOCATION = url;
        MATERIALSERVICESERVICE_EXCEPTION = e;
    }

    public MaterialServiceService() {
        super(__getWsdlLocation(), MATERIALSERVICESERVICE_QNAME);
    }

    public MaterialServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATERIALSERVICESERVICE_QNAME, features);
    }

    public MaterialServiceService(URL wsdlLocation) {
        super(wsdlLocation, MATERIALSERVICESERVICE_QNAME);
    }

    public MaterialServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATERIALSERVICESERVICE_QNAME, features);
    }

    public MaterialServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MaterialServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MaterialService
     */
    @WebEndpoint(name = "MaterialServicePort")
    public MaterialService getMaterialServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "MaterialServicePort"), MaterialService.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns MaterialService
     */
    @WebEndpoint(name = "MaterialServicePort")
    public MaterialService getMaterialServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "MaterialServicePort"), MaterialService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATERIALSERVICESERVICE_EXCEPTION!= null) {
            throw MATERIALSERVICESERVICE_EXCEPTION;
        }
        return MATERIALSERVICESERVICE_WSDL_LOCATION;
    }

}
