
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/ProviderService?wsdl")
public class ProviderServiceService
    extends Service
{

    private final static URL PROVIDERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERSERVICESERVICE_EXCEPTION;
    private final static QName PROVIDERSERVICESERVICE_QNAME = new QName("http://endpoint.service/", "ProviderServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/ProviderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROVIDERSERVICESERVICE_WSDL_LOCATION = url;
        PROVIDERSERVICESERVICE_EXCEPTION = e;
    }

    public ProviderServiceService() {
        super(__getWsdlLocation(), PROVIDERSERVICESERVICE_QNAME);
    }

    public ProviderServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERSERVICESERVICE_QNAME, features);
    }

    public ProviderServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERSERVICESERVICE_QNAME);
    }

    public ProviderServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERSERVICESERVICE_QNAME, features);
    }

    public ProviderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderService
     */
    @WebEndpoint(name = "ProviderServicePort")
    public ProviderService getProviderServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "ProviderServicePort"), ProviderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns ProviderService
     */
    @WebEndpoint(name = "ProviderServicePort")
    public ProviderService getProviderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "ProviderServicePort"), ProviderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERSERVICESERVICE_EXCEPTION!= null) {
            throw PROVIDERSERVICESERVICE_EXCEPTION;
        }
        return PROVIDERSERVICESERVICE_WSDL_LOCATION;
    }

}
