
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.ListOfProvider;
import types.Provider;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProviderService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface ProviderService {


    /**
     * 
     * @return
     *     returns types.ListOfProvider
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProvider", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllProvider")
    @ResponseWrapper(localName = "getAllProviderResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllProviderResponse")
    @Action(input = "http://endpoint.service/ProviderService/getAllProviderRequest", output = "http://endpoint.service/ProviderService/getAllProviderResponse")
    public ListOfProvider getAllProvider();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfProvider
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProvider", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DeleteProvider")
    @ResponseWrapper(localName = "deleteProviderResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DeleteProviderResponse")
    @Action(input = "http://endpoint.service/ProviderService/deleteProviderRequest", output = "http://endpoint.service/ProviderService/deleteProviderResponse")
    public ListOfProvider deleteProvider(
        @WebParam(name = "arg0", targetNamespace = "")
        Provider arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfProvider
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewProvider", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewProvider")
    @ResponseWrapper(localName = "setNewProviderResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewProviderResponse")
    @Action(input = "http://endpoint.service/ProviderService/setNewProviderRequest", output = "http://endpoint.service/ProviderService/setNewProviderResponse")
    public ListOfProvider setNewProvider(
        @WebParam(name = "arg0", targetNamespace = "")
        Provider arg0);

}
