
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.ListOfStaff;
import types.Staff;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StaffService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface StaffService {


    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotal", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetTotal")
    @ResponseWrapper(localName = "getTotalResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetTotalResponse")
    @Action(input = "http://endpoint.service/StaffService/getTotalRequest", output = "http://endpoint.service/StaffService/getTotalResponse")
    public double getTotal();

    /**
     * 
     * @return
     *     returns types.ListOfStaff
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStaff", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllStaff")
    @ResponseWrapper(localName = "getAllStaffResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllStaffResponse")
    @Action(input = "http://endpoint.service/StaffService/getAllStaffRequest", output = "http://endpoint.service/StaffService/getAllStaffResponse")
    public ListOfStaff getAllStaff();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfStaff
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewStaff", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewStaff")
    @ResponseWrapper(localName = "setNewStaffResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewStaffResponse")
    @Action(input = "http://endpoint.service/StaffService/setNewStaffRequest", output = "http://endpoint.service/StaffService/setNewStaffResponse")
    public ListOfStaff setNewStaff(
        @WebParam(name = "arg0", targetNamespace = "")
        Staff arg0);

}
