
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StaffServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/StaffService?wsdl")
public class StaffServiceService
    extends Service
{

    private final static URL STAFFSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException STAFFSERVICESERVICE_EXCEPTION;
    private final static QName STAFFSERVICESERVICE_QNAME = new QName("http://endpoint.service/", "StaffServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/StaffService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STAFFSERVICESERVICE_WSDL_LOCATION = url;
        STAFFSERVICESERVICE_EXCEPTION = e;
    }

    public StaffServiceService() {
        super(__getWsdlLocation(), STAFFSERVICESERVICE_QNAME);
    }

    public StaffServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STAFFSERVICESERVICE_QNAME, features);
    }

    public StaffServiceService(URL wsdlLocation) {
        super(wsdlLocation, STAFFSERVICESERVICE_QNAME);
    }

    public StaffServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STAFFSERVICESERVICE_QNAME, features);
    }

    public StaffServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StaffServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StaffService
     */
    @WebEndpoint(name = "StaffServicePort")
    public StaffService getStaffServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "StaffServicePort"), StaffService.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns StaffService
     */
    @WebEndpoint(name = "StaffServicePort")
    public StaffService getStaffServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "StaffServicePort"), StaffService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STAFFSERVICESERVICE_EXCEPTION!= null) {
            throw STAFFSERVICESERVICE_EXCEPTION;
        }
        return STAFFSERVICESERVICE_WSDL_LOCATION;
    }

}
