/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import service.endpoint.*;
import types.*;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class main extends javax.swing.JFrame {

    static DefaultTableModel model = new DefaultTableModel();
    static ActionServiceService actionService = null;
    static BranchServiceService branchService = null;
    static MaterialServiceService materialService = null;
    static ProviderServiceService providerService = null;
    static StaffServiceService staffService = null;

    static {
        actionService = new ActionServiceService();
        branchService = new BranchServiceService();
        materialService = new MaterialServiceService();
        providerService = new ProviderServiceService();
        staffService = new StaffServiceService();
    }

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personal_dialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        personal_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        add_personal_button = new javax.swing.JButton();
        fio_textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        age_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        position_combobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        salary_textfield = new javax.swing.JTextField();
        delete_staff_button = new javax.swing.JButton();
        count_zp_button = new javax.swing.JButton();
        zp_label = new javax.swing.JLabel();
        actions_dialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        actions_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        desc_textfield = new javax.swing.JTextField();
        fasa = new javax.swing.JLabel();
        price_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        time_numericupdown = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        venik_combobox = new javax.swing.JComboBox<>();
        add_action_button = new javax.swing.JButton();
        delete_actuion_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        avg_label = new javax.swing.JLabel();
        veniki_dialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        veniki_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        veniki_desc_textfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tree_textfield = new javax.swing.JTextField();
        add_venik_button = new javax.swing.JButton();
        delete_venik_button = new javax.swing.JButton();
        postavshiki_dialog = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        postavshiki_table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        postavshik_textfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rashodniki_combobox = new javax.swing.JComboBox<>();
        add_postavshik_button = new javax.swing.JButton();
        delete_postavshik_button = new javax.swing.JButton();
        count_sotr = new javax.swing.JButton();
        avg_sotr_label = new javax.swing.JLabel();
        rash_dialog = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        rash_table = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        rash_textfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rash_desc_textfield = new javax.swing.JTextField();
        add_rash_button = new javax.swing.JButton();
        delete_rash_button = new javax.swing.JButton();
        staff_button = new javax.swing.JButton();
        actions_button = new javax.swing.JButton();
        veniki_button = new javax.swing.JButton();
        postavshiki_button = new javax.swing.JButton();
        rash_button = new javax.swing.JButton();
        rash_amount_textfield = new javax.swing.JTextField();
        postavshik_coop_textfield = new javax.swing.JTextField();

        personal_dialog.setResizable(false);
        personal_dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                personal_dialogWindowOpened(evt);
            }
        });

        personal_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "���", "�������", "���������", "�/�"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(personal_table);

        jLabel1.setText("���");

        add_personal_button.setText("��������");
        add_personal_button.setToolTipText("");
        add_personal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_personal_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("�������");

        jLabel3.setText("���������");

        position_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "�������������", "�����������", "��������", "���������" }));

        jLabel4.setText("���������� �����");

        delete_staff_button.setText("�������");
       /*delete_staff_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_staff_buttonActionPerformed(evt);
            }
        });*/

        count_zp_button.setText("��������� ������ �/�");
        count_zp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_zp_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personal_dialogLayout = new javax.swing.GroupLayout(personal_dialog.getContentPane());
        personal_dialog.getContentPane().setLayout(personal_dialogLayout);
        personal_dialogLayout.setHorizontalGroup(
            personal_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(count_zp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fio_textfield)
                    .addComponent(age_textfield)
                    .addComponent(position_combobox, 0, 280, Short.MAX_VALUE)
                    .addComponent(salary_textfield)
                    .addGroup(personal_dialogLayout.createSequentialGroup()
                        .addComponent(add_personal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_staff_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(personal_dialogLayout.createSequentialGroup()
                        .addGroup(personal_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(zp_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        personal_dialogLayout.setVerticalGroup(
            personal_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fio_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(age_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(position_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salary_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_personal_button)
                    .addComponent(delete_staff_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count_zp_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zp_label)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        actions_dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                actions_dialogWindowOpened(evt);
            }
        });

        actions_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "������", "����", "������������", "��� ������"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        actions_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(actions_table);

        jLabel5.setText("������");

        fasa.setText("����");

        jLabel6.setText("������������");

        time_numericupdown.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 4.0d, 0.0d));

        jLabel7.setText("�����");

        add_action_button.setText("��������");
        add_action_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_action_buttonActionPerformed(evt);
            }
        });

        delete_actuion_button.setText("�������");
        /*
        delete_actuion_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_actuion_buttonActionPerformed(evt);
            }
        });*/

        jButton1.setText("��������� ������� ��������� ������");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actions_dialogLayout = new javax.swing.GroupLayout(actions_dialog.getContentPane());
        actions_dialog.getContentPane().setLayout(actions_dialogLayout);
        actions_dialogLayout.setHorizontalGroup(
            actions_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actions_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(actions_dialogLayout.createSequentialGroup()
                        .addGroup(actions_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(desc_textfield)
                            .addComponent(fasa)
                            .addComponent(price_textfield)
                            .addComponent(jLabel6)
                            .addComponent(time_numericupdown, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(venik_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(actions_dialogLayout.createSequentialGroup()
                                .addComponent(add_action_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete_actuion_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(actions_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(avg_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        actions_dialogLayout.setVerticalGroup(
            actions_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actions_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desc_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actions_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(actions_dialogLayout.createSequentialGroup()
                        .addComponent(fasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(actions_dialogLayout.createSequentialGroup()
                        .addComponent(avg_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time_numericupdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(venik_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(actions_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_action_button)
                    .addComponent(delete_actuion_button))
                .addContainerGap())
        );

        veniki_dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                veniki_dialogWindowOpened(evt);
            }
        });

        veniki_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "��������", "������ ��� ������������"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(veniki_table);

        jLabel8.setText("��������");

        jLabel9.setText("������ ��� ������������");

        add_venik_button.setText("��������");
        add_venik_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_venik_buttonActionPerformed(evt);
            }
        });

        delete_venik_button.setText("�������");
        /*
        delete_venik_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_venik_buttonActionPerformed(evt);
            }
        });*/

        javax.swing.GroupLayout veniki_dialogLayout = new javax.swing.GroupLayout(veniki_dialog.getContentPane());
        veniki_dialog.getContentPane().setLayout(veniki_dialogLayout);
        veniki_dialogLayout.setHorizontalGroup(
            veniki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veniki_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(veniki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(veniki_desc_textfield)
                    .addComponent(tree_textfield)
                    .addGroup(veniki_dialogLayout.createSequentialGroup()
                        .addGroup(veniki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(veniki_dialogLayout.createSequentialGroup()
                                .addComponent(add_venik_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete_venik_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        veniki_dialogLayout.setVerticalGroup(
            veniki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veniki_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veniki_desc_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tree_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(veniki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_venik_button)
                    .addComponent(delete_venik_button))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        postavshiki_dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                postavshiki_dialogWindowOpened(evt);
            }
        });

        postavshiki_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "����������������� ��������������", "���������", "����� ��������"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(postavshiki_table);

        jLabel10.setText("���������");

        jLabel11.setText("�����");

        add_postavshik_button.setText("��������");
        add_postavshik_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_postavshik_buttonActionPerformed(evt);
            }
        });

        delete_postavshik_button.setText("�������");
        /*
        delete_postavshik_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_postavshik_buttonActionPerformed(evt);
            }
        });*/

        count_sotr.setText("��������� ������� ����� ��������������");
        /*
        count_sotr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_sotrActionPerformed(evt);
            }
        });*/

        javax.swing.GroupLayout postavshiki_dialogLayout = new javax.swing.GroupLayout(postavshiki_dialog.getContentPane());
        postavshiki_dialog.getContentPane().setLayout(postavshiki_dialogLayout);
        postavshiki_dialogLayout.setHorizontalGroup(
            postavshiki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postavshiki_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(postavshiki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(postavshiki_dialogLayout.createSequentialGroup()
                        .addGroup(postavshiki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(postavshik_textfield)
                            .addComponent(jLabel11)
                            .addComponent(rashodniki_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_postavshik_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete_postavshik_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(count_sotr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(avg_sotr_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 347, Short.MAX_VALUE)))
                .addContainerGap())
        );
        postavshiki_dialogLayout.setVerticalGroup(
            postavshiki_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postavshiki_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postavshik_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rashodniki_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_postavshik_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_postavshik_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count_sotr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avg_sotr_label, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        rash_dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                rash_dialogWindowOpened(evt);
            }
        });

        rash_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "�����", "��������"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(rash_table);

        jLabel12.setText("�����");

        jLabel13.setText("��������");

        add_rash_button.setText("��������");
        add_rash_button.setToolTipText("");
        add_rash_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_rash_buttonActionPerformed(evt);
            }
        });

        delete_rash_button.setText("�������");
        /*
        delete_rash_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_rash_buttonActionPerformed(evt);
            }
        });*/

        javax.swing.GroupLayout rash_dialogLayout = new javax.swing.GroupLayout(rash_dialog.getContentPane());
        rash_dialog.getContentPane().setLayout(rash_dialogLayout);
        rash_dialogLayout.setHorizontalGroup(
            rash_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rash_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rash_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(rash_dialogLayout.createSequentialGroup()
                        .addGroup(rash_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(rash_textfield)
                            .addComponent(jLabel13)
                            .addComponent(rash_desc_textfield)
                            .addComponent(add_rash_button, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(delete_rash_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rash_dialogLayout.setVerticalGroup(
            rash_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rash_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rash_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rash_desc_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_rash_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_rash_button)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 500));
        setResizable(false);

        staff_button.setText("����������");
        staff_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_buttonActionPerformed(evt);
            }
        });

        actions_button.setText("������");
        actions_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actions_buttonActionPerformed(evt);
            }
        });

        veniki_button.setText("������");
        veniki_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veniki_buttonActionPerformed(evt);
            }
        });

        postavshiki_button.setText("����������");
        postavshiki_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postavshiki_buttonActionPerformed(evt);
            }
        });

        rash_button.setText("��������� ���������");
        rash_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rash_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staff_button, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(actions_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(veniki_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(postavshiki_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rash_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(staff_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actions_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veniki_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postavshiki_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rash_button)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staff_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_buttonActionPerformed
        // TODO add your handling code here:
        personal_dialog.setSize(400, 600);
        personal_dialog.setVisible(true);
        
    }//GEN-LAST:event_staff_buttonActionPerformed

    private void actions_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actions_buttonActionPerformed
        // TODO add your handling code here:
        actions_dialog.setSize(650,550);
        actions_dialog.setVisible(true);
        
    }//GEN-LAST:event_actions_buttonActionPerformed

    private void actions_dialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_actions_dialogWindowOpened
        // TODO add your handling code here:
        model = null;
        model = (DefaultTableModel)actions_table.getModel();

        try {
            actions_output(actionService.getActionServicePort().getAllAction());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_actions_dialogWindowOpened

    private void add_action_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_action_buttonActionPerformed
        // TODO add your handling code here:
        model = null;
        model = (DefaultTableModel)actions_table.getModel();
        try{
            Action tmp = new Action();
            tmp.setDescription(desc_textfield.getText());
            tmp.setPrice(Double.parseDouble(price_textfield.getText()));
            tmp.setTime(Double.parseDouble(time_numericupdown.getValue().toString()));
            tmp.setVenik(venik_combobox.getSelectedItem().toString());
            actionService.getActionServicePort().setNewAction(tmp);
            actions_output(actionService.getActionServicePort().getAllAction());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_add_action_buttonActionPerformed

    private void veniki_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veniki_buttonActionPerformed
        // TODO add your handling code here:
        veniki_dialog.setSize(600, 500);
        veniki_dialog.setVisible(true);
    }//GEN-LAST:event_veniki_buttonActionPerformed

    private void veniki_dialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_veniki_dialogWindowOpened
        // TODO add your handling code here:
        model = null;
        model = (DefaultTableModel)veniki_table.getModel();
        veniki_output(branchService.getBranchServicePort().getAllBranch());
    }//GEN-LAST:event_veniki_dialogWindowOpened

    private void add_venik_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_venik_buttonActionPerformed
        // TODO add your handling code here:
        try{
            Branch tmp = new Branch();
            tmp.setDescription(veniki_desc_textfield.getText());
            tmp.setTree((tree_textfield.getText()));
            branchService.getBranchServicePort().setNewBranch(tmp);
            veniki_output(branchService.getBranchServicePort().getAllBranch());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_add_venik_buttonActionPerformed

    private void postavshiki_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postavshiki_buttonActionPerformed
        // TODO add your handling code here:
        postavshiki_dialog.setSize(600,600);
        postavshiki_dialog.setVisible(true);
    }//GEN-LAST:event_postavshiki_buttonActionPerformed

    private void rash_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rash_buttonActionPerformed
        // TODO add your handling code here:
        rash_dialog.setSize(600, 500);
        rash_dialog.setVisible(true);
    }//GEN-LAST:event_rash_buttonActionPerformed

    private void postavshiki_dialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_postavshiki_dialogWindowOpened
        // TODO add your handling code here:
        model = null;
        model = (DefaultTableModel)postavshiki_table.getModel();
        try{
            postavshiki_output(providerService.getProviderServicePort().getAllProvider());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_postavshiki_dialogWindowOpened

    private void add_postavshik_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_postavshik_buttonActionPerformed
        // TODO add your handling code here:
        try{
            Provider tmp = new Provider();
            tmp.setName(postavshik_textfield.getText());
            tmp.setProduct(rashodniki_combobox.getSelectedItem().toString());
            tmp.setCooperation((Integer.parseInt(postavshik_coop_textfield.getText())));
            providerService.getProviderServicePort().setNewProvider(tmp);
            postavshiki_output(providerService.getProviderServicePort().getAllProvider());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_add_postavshik_buttonActionPerformed

    private void add_rash_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_rash_buttonActionPerformed
        // TODO add your handling code here:
        try{
            Material tmp = new Material();
            tmp.setName(rash_textfield.getText());
            tmp.setAmount(Integer.parseInt(rash_amount_textfield.getText()));
            tmp.setDescription(rash_desc_textfield.getText());
            tmp.setPrice(Double.parseDouble(price_textfield.getText()));
            materialService.getMaterialServicePort().setNewMaterial(tmp);
            rashodniki_output(materialService.getMaterialServicePort().getAllMaterials());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_add_rash_buttonActionPerformed

    private void rash_dialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_rash_dialogWindowOpened
        // TODO add your handling code here:
        model = null;
        model = (DefaultTableModel)rash_table.getModel();
        rashodniki_output(materialService.getMaterialServicePort().getAllMaterials());
    }//GEN-LAST:event_rash_dialogWindowOpened

    private void personal_dialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_personal_dialogWindowOpened
        // TODO add your handling code here:
        model = null;
        model = (DefaultTableModel)personal_table.getModel();
        personal_output(staffService.getStaffServicePort().getAllStaff());

    }//GEN-LAST:event_personal_dialogWindowOpened

    private void add_personal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_personal_buttonActionPerformed
        // TODO add your handling code here:
        try{
            Staff tmp = new Staff();
            tmp.setFIO(fio_textfield.getText());
            tmp.setAge(Integer.parseInt(age_textfield.getText()));
            tmp.setPosition(position_combobox.getSelectedItem().toString());
            tmp.setSalary( Double.parseDouble(salary_textfield.getText()));
            staffService.getStaffServicePort().setNewStaff(tmp);
            personal_output(staffService.getStaffServicePort().getAllStaff());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_add_personal_buttonActionPerformed

    /*private void delete_staff_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_staff_buttonActionPerformed
        // TODO add your handling code here:
        try{
        c.deletePersonal(fio_textfield.getText());}
        catch(Exception ex){
            ex.printStackTrace();
        }
        personal_output();
    }//GEN-LAST:event_delete_staff_buttonActionPerformed*/

    private void count_zp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_zp_buttonActionPerformed
        // TODO add your handling code here:
        try{
        zp_label.setText(Double.toString(staffService.getStaffServicePort().getTotal()));
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_count_zp_buttonActionPerformed

   /* private void delete_actuion_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_actuion_buttonActionPerformed
        // TODO add your handling code here:
        try{
        c.deleteUsluga(desc_textfield.getText());}
                catch(Exception ex){
            ex.printStackTrace();
        }
        actions_output();
    }
    //GEN-LAST:event_delete_actuion_buttonActionPerformed
    */

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        avg_label.setText(Double.toString(actionService.getActionServicePort().getTotal()));
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /*private void delete_venik_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_venik_buttonActionPerformed
        // TODO add your handling code here:
        try{
        c.deleteVenik(tree_textfield.getText());}
                catch(Exception ex){
            ex.printStackTrace();
        }
        veniki_output();
    }//GEN-LAST:event_delete_venik_buttonActionPerformed*/

   /* private void delete_postavshik_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_postavshik_buttonActionPerformed
        // TODO add your handling code here:
        try{
        c.deletePostavshik(postavshik_textfield.getText());}
                catch(Exception ex){
            ex.printStackTrace();
        }
        postavshiki_output();
    }//GEN-LAST:event_delete_postavshik_buttonActionPerformed*/

   /* private void count_sotrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_sotrActionPerformed
        // TODO add your handling code here:
        try {
            avg_sotr_label.setText(c.countSotr());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_count_sotrActionPerformed*/

   /*
    private void delete_rash_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_rash_buttonActionPerformed
        // TODO add your handling code here:
        try{
        c.deleteRash(rash_textfield.getText());}        catch(Exception ex){
            ex.printStackTrace();
        }
        rashodniki_output();
    }//GEN-LAST:event_delete_rash_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    
    private void veniki_output(ListOfBranch lst){
        ClearTable();
        int i = 1;
        try
        {
            for(Branch tmp: lst.getItem()){
                Object[] row = new Object[3];
                row[0] = i++;
                row[1] = tmp.getDescription();
                row[2] = tmp.getTree();
                model.addRow(row);
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void actions_output(ListOfAction lst){
        ClearTable();
        int i = 1;
        try
        {
            for(Action tmp: lst.getItem()){
                Object[] row = new Object[5];
                row[0] = i++;
                row[1] = tmp.getDescription();
                row[2] = tmp.getPrice();
                row[3] = tmp.getTime();
                row[4] = tmp.getVenik();
                model.addRow(row);
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void personal_output(ListOfStaff lst){
        ClearTable();
        int i = 1;
        try{
            for(Staff tmp: lst.getItem()){
                Object[] row = new Object[5];
                row[0] = i++;
                row[1] = tmp.getFIO();
                row[2] = tmp.getAge();
                row[3] = tmp.getPosition();
                row[4] = tmp.getSalary();
                model.addRow(row);
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void rashodniki_output(ListOfMaterial lst){
        ClearTable();
        int i = 1;
        try
        {
            for(Material tmp: lst.getItem()){
                Object[] row = new Object[5];
                row[0] = i++;
                row[1] = tmp.getName();
                row[2] = tmp.getDescription();
                row[3] = tmp.getPrice();
                row[4] = tmp.getAmount();
                model.addRow(row);
            }
        }
                catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void postavshiki_output(ListOfProvider lst){
        ClearTable();
        int i = 1;
        try
        {
            for(Provider tmp : lst.getItem()){
                Object[] row = new Object[4];
                row[0] = i++;
                row[1] = tmp.getName();
                row[2] = tmp.getCooperation();
                row[3] = tmp.getProduct();
                model.addRow(row);
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void ClearTable(){
      while (model.getRowCount()>0){
          model.removeRow(0);
      }   
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actions_button;
    private javax.swing.JDialog actions_dialog;
    private javax.swing.JTable actions_table;
    private javax.swing.JButton add_action_button;
    private javax.swing.JButton add_personal_button;
    private javax.swing.JButton add_postavshik_button;
    private javax.swing.JButton add_rash_button;
    private javax.swing.JButton add_venik_button;
    private javax.swing.JTextField age_textfield;
    private javax.swing.JLabel avg_label;
    private javax.swing.JLabel avg_sotr_label;
    private javax.swing.JButton count_sotr;
    private javax.swing.JButton count_zp_button;
    private javax.swing.JButton delete_actuion_button;
    private javax.swing.JButton delete_postavshik_button;
    private javax.swing.JButton delete_rash_button;
    private javax.swing.JButton delete_staff_button;
    private javax.swing.JButton delete_venik_button;
    private javax.swing.JTextField desc_textfield;
    private javax.swing.JLabel fasa;
    private javax.swing.JTextField fio_textfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog personal_dialog;
    private javax.swing.JTable personal_table;
    private javax.swing.JComboBox<String> position_combobox;
    private javax.swing.JTextField postavshik_textfield;
    private javax.swing.JButton postavshiki_button;
    private javax.swing.JDialog postavshiki_dialog;
    private javax.swing.JTable postavshiki_table;
    private javax.swing.JTextField price_textfield;
    private javax.swing.JButton rash_button;
    private javax.swing.JTextField rash_desc_textfield;
    private javax.swing.JDialog rash_dialog;
    private javax.swing.JTable rash_table;
    private javax.swing.JTextField rash_textfield;
    private javax.swing.JComboBox<String> rashodniki_combobox;
    private javax.swing.JTextField salary_textfield;
    private javax.swing.JButton staff_button;
    private javax.swing.JSpinner time_numericupdown;
    private javax.swing.JTextField tree_textfield;
    private javax.swing.JComboBox<String> venik_combobox;
    private javax.swing.JButton veniki_button;
    private javax.swing.JTextField veniki_desc_textfield;
    private javax.swing.JDialog veniki_dialog;
    private javax.swing.JTable veniki_table;
    private javax.swing.JLabel zp_label;
    private javax.swing.JTextField rash_amount_textfield;
    private javax.swing.JTextField postavshik_coop_textfield;
    // End of variables declaration//GEN-END:variables
}
